### ISSUE TITLE
More Events

### ISSUE THREAD

**Issue by ThreeManager785** [tgymnich/SolarTime#1]
First of all I appreciate author to make this, which is really helpful to me. Thank you very much.

I saw `Event` in the source code:

```swift
public enum Event {
        case official
//        case civil
//        case nautical
//        case astronimical
    }
```

I want to ask if this package will still be maintained and make more events available, or they are not considered anymore?

**Comment by tgymnich** [comment]
I don't intend to maintain this package.
This was just the library part of a demo project for a server-side Swift framework I worked on during a Uni project.

**Comment by ThreeManager785** [comment]
Okay, thank you.
